version: '3.1'

services:

  banco-de-dados:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: desenvolvimento
      POSTGRES_USER: desenvolvimento
      POSTGRES_DB: desafio
    volumes:
      - ./database/tabelas.sql:/docker-entrypoint-initdb.d/tabelas.sql
      - banco-de-dados-volume:/var/lib/postgresql/data
  servico:
    build: .
    restart: always
    ports:
      - 7080:8080
    environment:
      PORT: 8080
      DATABASE: desafio
      USUARIO: desenvolvimento
      SENHA: desenvolvimento
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  banco-de-dados-volume: